# Understanding the RDBMS
A **Relational Database Management System (RDBMS)** is a type of database that stores data in a structured format using tables, rows, and columns. It ensures data integrity and allows efficient retrieval using **Structured Query Language (SQL)**.

## Key Features:
- **Tables:** Data is stored in tables with rows and columns.
- **Primary Key:** Uniquely identifies each record in a table.
- **Foreign Key:** Establishes a relationship between tables.
- **Indexes:** Improves search performance.
- **Transactions:** Ensures operations follow **ACID** (Atomicity, Consistency, Isolation, Durability).

### Example:
Consider a **Students** table:

| StudentID | Name    | Age | Course   |
|-----------|--------|----|---------|
| 1         | Alice  | 22 | CS      |
| 2         | Bob    | 21 | IT      |
| 3         | Charlie| 23 | CS      |

---
# Database Normalization
**Normalization** is the process of structuring a relational database to reduce redundancy and improve data integrity.

## **Normalization Forms:**
1. **1NF (First Normal Form)**: Each column must contain atomic values (no multiple values in one column).
2. **2NF (Second Normal Form)**: All non-key attributes must depend on the primary key.
3. **3NF (Third Normal Form)**: No transitive dependency (attributes must depend only on the primary key).

### Example (Before Normalization):
| StudentID | Name  | Course   | Instructor |
|-----------|------|---------|------------|
| 1         | Alice| CS      | Dr. Smith  |
| 2         | Bob  | IT      | Dr. Brown  |
| 3         | Charlie| CS   | Dr. Smith  |

Here, **Instructor** depends on **Course**, not **StudentID**, violating **3NF**.

### Example (After Normalization):
#### **Students Table**
| StudentID | Name  |
|-----------|------|
| 1         | Alice |
| 2         | Bob   |
| 3         | Charlie |

#### **Courses Table**
| CourseID | Course   | Instructor  |
|----------|---------|-------------|
| 101      | CS      | Dr. Smith   |
| 102      | IT      | Dr. Brown   |

---
# Select Statement
The `SELECT` statement retrieves data from a database.

### **Basic Syntax**
```sql
SELECT column1, column2 FROM table_name;

# Database Normalization Levels with Examples

Normalization is the process of structuring a relational database to reduce redundancy and improve data integrity. The most common normal forms are:

---

# **1NF (First Normal Form)**
### **Rules:**
- Each column should have atomic (indivisible) values.
- Each row must have a unique identifier (Primary Key).
- No repeating groups or arrays.

### **Example (Before 1NF - Violating Atomicity)**
| StudentID | Name  | Course      |
|-----------|------|-------------|
| 1         | Alice | CS, Math    |
| 2         | Bob   | IT, Physics |
| 3         | Charlie | CS        |

### **Solution (Convert to 1NF)**
Each course must be stored in a separate row.

| StudentID | Name  | Course  |
|-----------|------|--------|
| 1         | Alice | CS     |
| 1         | Alice | Math   |
| 2         | Bob   | IT     |
| 2         | Bob   | Physics|
| 3         | Charlie | CS   |

✅ **Now, the table follows 1NF as all fields contain atomic values.**

---

# **2NF (Second Normal Form)**
### **Rules:**
- Table must be in 1NF.
- Non-key attributes must depend entirely on the primary key.
- Remove **partial dependencies** (where a non-key column depends on part of a composite primary key).

### **Example (Before 2NF - Partial Dependency)**
| StudentID | Course  | Instructor |
|-----------|--------|------------|
| 1         | CS     | Dr. Smith  |
| 1         | Math   | Dr. Johnson|
| 2         | IT     | Dr. Brown  |

Here, **Instructor** depends on **Course**, not on **StudentID**.

### **Solution (Convert to 2NF)**
Split into two tables:

#### **Students Table**
| StudentID | Name  |
|-----------|------|
| 1         | Alice |
| 2         | Bob   |

#### **Courses Table**
| CourseID | Course  | Instructor  |
|----------|--------|------------|
| 101      | CS     | Dr. Smith  |
| 102      | Math   | Dr. Johnson|
| 103      | IT     | Dr. Brown  |

#### **Student-Course Relationship Table**
| StudentID | CourseID |
|-----------|---------|
| 1         | 101     |
| 1         | 102     |
| 2         | 103     |

✅ **Now, non-key columns depend only on the primary key, removing partial dependency.**

---

# **3NF (Third Normal Form)**
### **Rules:**
- Table must be in 2NF.
- No **transitive dependency** (non-key attributes should depend only on the primary key, not on other non-key attributes).

### **Example (Before 3NF - Transitive Dependency)**
| StudentID | Name  | Course  | Instructor | InstructorContact |
|-----------|------|--------|------------|------------------|
| 1         | Alice | CS     | Dr. Smith  | 123-456-7890    |
| 2         | Bob   | IT     | Dr. Brown  | 987-654-3210    |

Here, **InstructorContact** depends on **Instructor**, not directly on **StudentID**.

### **Solution (Convert to 3NF)**
Split into separate tables:

#### **Students Table**
| StudentID | Name  |
|-----------|------|
| 1         | Alice |
| 2         | Bob   |

#### **Courses Table**
| CourseID | Course  | InstructorID |
|----------|--------|--------------|
| 101      | CS     | 1            |
| 102      | IT     | 2            |

#### **Instructors Table**
| InstructorID | Instructor | InstructorContact |
|-------------|------------|------------------|
| 1           | Dr. Smith  | 123-456-7890    |
| 2           | Dr. Brown  | 987-654-3210    |

✅ **Now, all non-key attributes depend only on the primary key, removing transitive dependency.**

---

# **BCNF (Boyce-Codd Normal Form)**
### **Rules:**
- Table must be in 3NF.
- Every determinant must be a candidate key.

### **Example (Before BCNF - Violation)**
| StudentID | Course  | Instructor |
|-----------|--------|------------|
| 1         | CS     | Dr. Smith  |
| 2         | CS     | Dr. Johnson|

Here, **Course** determines **Instructor**, but **Course** is not a candidate key.

### **Solution (Convert to BCNF)**
Break into two tables:

#### **Course-Instructor Table**
| CourseID | Course  | InstructorID |
|----------|--------|--------------|
| 101      | CS     | 1            |
| 101      | CS     | 2            |

#### **Instructors Table**
| InstructorID | Instructor |
|-------------|------------|
| 1           | Dr. Smith  |
| 2           | Dr. Johnson|

✅ **Now, all functional dependencies are properly managed.**

---

# **Conclusion**
| Normal Form | Issue Solved |
|-------------|-------------|
| **1NF**  | Removes repeating groups, ensures atomic values. |
| **2NF**  | Removes partial dependencies. |
| **3NF**  | Removes transitive dependencies. |
| **BCNF** | Ensures every determinant is a candidate key. |

Normalization improves **data consistency**, **reduces redundancy**, and **enhances database efficiency**.

# DB VS File system (why use a DB)

In [ ]:
import sqlite3

# Connect to SQLite database (or create one if it doesn't exist)
conn = sqlite3.connect("example.db")
cursor = conn.cursor()

# Understanding the RDBMS & Database Normalization
# Create a normalized database with two tables: Users and Orders

cursor.execute("""
CREATE TABLE IF NOT EXISTS Users (
    user_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS Orders (
    order_id INTEGER PRIMARY KEY,
    user_id INTEGER,
    product TEXT NOT NULL,
    price REAL NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
)
""")

# Insert sample data
cursor.execute("INSERT INTO Users (name, email) VALUES ('Alice', 'alice@example.com')")
cursor.execute("INSERT INTO Users (name, email) VALUES ('Bob', 'bob@example.com')")

cursor.execute("INSERT INTO Orders (user_id, product, price) VALUES (1, 'Laptop', 1200.00)")
cursor.execute("INSERT INTO Orders (user_id, product, price) VALUES (2, 'Phone', 800.00)")
cursor.execute("INSERT INTO Orders (user_id, product, price) VALUES (1, 'Mouse', 25.00)")

# Commit the changes
conn.commit()

# Select Statement
print("All Orders:")
cursor.execute("SELECT * FROM Orders")
for row in cursor.fetchall():
    print(row)

# Where Clause: Get orders for a specific user
print("\nOrders for user Alice:")
cursor.execute("SELECT * FROM Orders WHERE user_id = 1")
for row in cursor.fetchall():
    print(row)

# Order By: Get orders sorted by price (descending)
print("\nOrders sorted by price (desc):")
cursor.execute("SELECT * FROM Orders ORDER BY price DESC")
for row in cursor.fetchall():
    print(row)

# Close the connection
conn.close()

All Orders:
(1, 1, 'Laptop', 1200.0)
(2, 2, 'Phone', 800.0)
(3, 1, 'Mouse', 25.0)

Orders for user Alice:
(1, 1, 'Laptop', 1200.0)
(3, 1, 'Mouse', 25.0)

Orders sorted by price (desc):
(1, 1, 'Laptop', 1200.0)
(2, 2, 'Phone', 800.0)
(3, 1, 'Mouse', 25.0)

In [ ]:
import sqlite3
import os
import json
import csv
import time
import random
import string

# Configuration
DATA_SIZE = 10_000_000  # Number of dummy records
DB_FILE = "test.db"
CSV_FILE = "test.csv"
JSON_FILE = "test.json"

# Dummy Data Generator
def generate_dummy_data(size):
    return [
        {
            "id": i,
            "name": ''.join(random.choices(string.ascii_letters, k=10)),
            "email": ''.join(random.choices(string.ascii_letters, k=5)) + "@example.com",
            "age": random.randint(18, 70),
        }
        for i in range(size)
    ]

# 1. SQLite Database Operations
def sqlite_insert(data):
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("DROP TABLE IF EXISTS users")
    cursor.execute("CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, email TEXT, age INTEGER)")

    start_time = time.time()
    cursor.executemany("INSERT INTO users (id, name, email, age) VALUES (:id, :name, :email, :age)", data)
    conn.commit()
    conn.close()

    return time.time() - start_time

def sqlite_fetch():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()

    start_time = time.time()
    cursor.execute("SELECT * FROM users")
    data = cursor.fetchall()
    conn.close()

    return time.time() - start_time, len(data)

# 2. File System (CSV) Operations
def csv_write(data):
    start_time = time.time()
    with open(CSV_FILE, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "name", "email", "age"])
        writer.writeheader()
        writer.writerows(data)
    return time.time() - start_time

def csv_read():
    start_time = time.time()
    with open(CSV_FILE, "r") as f:
        reader = csv.DictReader(f)
        data = list(reader)
    return time.time() - start_time, len(data)

# 3. File System (JSON) Operations
def json_write(data):
    start_time = time.time()
    with open(JSON_FILE, "w") as f:
        json.dump(data, f)
    return time.time() - start_time

def json_read():
    start_time = time.time()
    with open(JSON_FILE, "r") as f:
        data = json.load(f)
    return time.time() - start_time, len(data)

# Run Performance Tests
dummy_data = generate_dummy_data(DATA_SIZE)

print(f"Data Size: {DATA_SIZE} Records\n")

# SQLite Performance
sqlite_time_insert = sqlite_insert(dummy_data)
sqlite_time_fetch, sqlite_count = sqlite_fetch()
print(f"SQLite Insert Time: {sqlite_time_insert:.4f} sec")
print(f"SQLite Fetch Time: {sqlite_time_fetch:.4f} sec ({sqlite_count} records)\n")

# CSV Performance
csv_time_write = csv_write(dummy_data)
csv_time_read, csv_count = csv_read()
print(f"CSV Write Time: {csv_time_write:.4f} sec")
print(f"CSV Read Time: {csv_time_read:.4f} sec ({csv_count} records)\n")

# JSON Performance
json_time_write = json_write(dummy_data)
json_time_read, json_count = json_read()
print(f"JSON Write Time: {json_time_write:.4f} sec")
print(f"JSON Read Time: {json_time_read:.4f} sec ({json_count} records)\n")

# Clean Up (Optional)
os.remove(DB_FILE)
os.remove(CSV_FILE)
os.remove(JSON_FILE)

Data Size: 10000000 Records

SQLite Insert Time: 28.6708 sec
SQLite Fetch Time: 14.3065 sec (10000000 records)

CSV Write Time: 35.3387 sec
CSV Read Time: 27.6609 sec (10000000 records)

JSON Write Time: 110.0928 sec
JSON Read Time: 15.4890 sec (10000000 records)

# OOP Example

In [ ]:
import sqlite3

# Step 1: Define a base class using OOP
class Database:
    def __init__(self, db_name="example.db"):  # Default Constructor
        self.db_name = db_name
        self.conn = sqlite3.connect(self.db_name)
        self.cursor = self.conn.cursor()
        self.create_table()

    def create_table(self):
        """Method to create a table"""
        self.cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                age INTEGER NOT NULL
            )
        """)
        self.conn.commit()

    def insert_user(self, name, age):
        """Method to insert a user"""
        self.cursor.execute("INSERT INTO users (name, age) VALUES (?, ?)", (name, age))
        self.conn.commit()

    def fetch_users(self):
        """Method to fetch all users"""
        self.cursor.execute("SELECT * FROM users")
        return self.cursor.fetchall()

    def close(self):
        """Method to close the database connection"""
        self.conn.close()


# Step 2: Define a subclass with Inheritance
class UserManager(Database):
    def __init__(self, db_name="example.db"):
        super().__init__(db_name)  # Calling parent constructor

    def display_users(self):
        """Method to display all users"""
        users = self.fetch_users()
        if not users:
            print("No users found!")
        else:
            for user in users:
                print(f"ID: {user[0]}, Name: {user[1]}, Age: {user[2]}")


# Step 3: Using the pass statement (Example Purpose)
class DummyClass:
    pass  # Placeholder for future implementation


# Step 4: Demonstrate parameterized constructor
class User:
    def __init__(self, name, age):  # Parameterized Constructor
        self.name = name
        self.age = age

    def get_details(self):
        """Method to return user details"""
        return f"User Name: {self.name}, Age: {self.age}"


# Step 5: Running the program
if __name__ == "__main__":
    db = UserManager()  # Create Database Instance (Inheritance)

    # Insert users
    db.insert_user("Alice", 25)
    db.insert_user("Bob", 30)

    # Display users
    print("User List from Database:")
    db.display_users()

    # Working with an object
    user1 = User("Charlie", 28)
    print(user1.get_details())

    # Closing the database connection
    db.close()